name: Build DEV version
run-name: Build DEV version

permissions: write-all

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    # 安装 rclone
    # dev版本不另外发release
    - name: Install rclone
      run: |
        cd ~
        curl https://rclone.org/install.sh | sudo bash
    # 配置 rclone
    - name: Configure rclone
      run: |
        mkdir -p ~/.config/rclone
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.RCLONECONFIG }}
        EOF
    - name: Sync to OneDrive
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        rclone mkdir one:/share/Mirouter-ui/dev/${{ github.sha }}
        rclone sync ./build one:/share/Mirouter-ui/dev/${{ github.sha }} 
